export const DESIGN_ALLOWABLES = {
	LEG_RATIO: 1,
	LEG_SLENDERNESS: 200,
	SADDLE_HORN_MPA: 150,
	SADDLE_FLEX_MPA: 100,
	SADDLE_COMP_MPA: 100,
	SKIRT_COMP_MPA: 100,
	SKIRT_CHAIR_MPA: 150,
	RING_FLEX_MPA: 150,
	RING_BASE_MPA: 15,
	LUG_FLEX_MPA: 150,
	ANCHOR_STEEL_RATIO: 1,
	ANCHOR_CONCRETE_RATIO: 1,
} as const;
